
GET http://localhost:8088/?id=101


### 获取用户信息
POST http://localhost:8080/
Content-Type: application/json

{
  "service": "cn.ipman.rpcman.demo.api.UserService",
  "methodSign": "findById@1_int",
  "args": [100]
}

### 获取订单信息
POST http://localhost:8080/
Content-Type: application/json

{
  "service": "cn.ipman.rpcman.demo.api.UserService",
  "methodSign": "findById@2_int_java.lang.String",
  "args": [200, "ipman"]
}
