server:
  port: 8088

rpcman:
  #providers: http://localhost:8080,http://localhost:8081,http://localhost:8082
  zk:
    zkServer: localhost:2181
    zkRoot: rpcman

  app:
    id: app1
    namespace: public
    env: dev
    version: 1.0
    useNetty: false

  consumer:
    retries: 2
    timeout: 200
    grayRatio: 33 # 灰度百分比 0-100
    faultLimit: 10 # 30s 内10次错误则隔离
    halfOpenInitialDelay: 10000 # 半开启初始延迟
    halfOpenDelay: 60000

logging:
  level:
    root: error
    cn.ipman.rpcman: info
