server:
  port: 8088

rpcman:
  providers: http://localhost:8080,http://localhost:8081,http://localhost:8082
  zkServer: localhost:2181
  zkRoot: rpcman

app:
  id: app1
  namespace: public
  env: dev
  version: 1.0
  retries: 2
  timeout: 1000

logging:
  level:
    root: info
    cn.ipman.rpcman: info
