server:
  port: 8080
  useNetty: true # open port = server.port + 1000

rpcman:
  zk:
    zkServer: localhost:2181
    zkRoot: rpcman

  app:
    id: app1
    namespace: public
    env: dev
    version: 1.0
    useNetty: true

  provider:
    metas:
      dc: bj
      gray: false
      unit: B001


logging:
  level:
    root: info
    cn.ipman.rpcman: debug
    io.netty: info