server:
  port: 8080
  useNetty: true # open port = server.port + 1000

rpcman:
  zkServer: localhost:2181
  zkRoot: rpcman

app:
  id: app1
  namespace: public
  env: dev
  version: 1.0
  metas: "{dc: 'bk', gray: 'true', unit: 'B001'}"


logging:
  level:
    root: info
    cn.ipman.rpcman: info